# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.6

env: 
  - DJANGO=2.1
  - DJANGO=2.1.1
  - DJANGO=2.1.2
  - DJANGO=2.1.3
  - DJANGO=2.1.4
  - DJANGO=2.1.5
  - DJANGO=2.1.7
matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install Django==$DJANGO
  - pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: CONF=travis tox
after_success:
  - codecov
